"""Pydantic models for structured LLM outputs, data validation, and policy enforcement.

This module defines the complete data contract for the ACRA retention workflow:
- CustomerProfile: customer account data
- RetentionOffer: proposed retention offer from the Strategist agent
- AuditResult: Financial Auditor's policy compliance verdict
- RetentionPayload: final structured output for database dispatch
- PolicyCheckResult: individual policy check outcome (programmatic)
"""

from pydantic import BaseModel, Field


class CustomerProfile(BaseModel):
    """Customer account data stored in the RAG vector database."""

    customer_id: str
    name: str
    email: str
    tenure_months: int
    plan_name: str
    monthly_cost_usd: float
    lifetime_value_usd: float
    support_tickets_last_90d: int
    feature_usage_score: float = Field(ge=0.0, le=1.0)
    payment_history: str  # "excellent", "good", "late", "delinquent"


class RetentionOffer(BaseModel):
    """A proposed retention offer generated by the Strategist agent.

    The `reasoning` field captures the agent's chain of thought - why it
    selected this particular offer given the customer context and policies.
    """

    discount_percent: int = Field(ge=0, le=100)
    duration_months: int = Field(ge=1, le=12)
    offer_type: str  # "discount", "free_months", "plan_downgrade", "feature_unlock"
    justification: str
    reasoning: str = ""  # agent's chain of thought for audit trail
    email_draft: str


class AuditResult(BaseModel):
    """Result of the Financial Auditor's policy compliance check.

    When `approved` is False, `policy_violations` contains the specific
    policy IDs and violation descriptions. `adjusted_offer` may contain
    a suggested correction for minor violations.
    """

    approved: bool
    feedback: str
    policy_violations: list[str] = Field(default_factory=list)
    adjusted_offer: RetentionOffer | None = None


class RetentionPayload(BaseModel):
    """Final structured JSON payload for database update and email dispatch."""

    customer_id: str
    customer_name: str
    original_reason: str
    final_offer: RetentionOffer
    audit_approved: bool
    email_to_send: str
    db_update: dict = Field(default_factory=dict)


class PolicyCheckResult(BaseModel):
    """Outcome of a single programmatic policy check.

    Used internally by the Auditor to build the aggregated AuditResult.
    """

    policy_id: str
    policy_title: str
    passed: bool
    violation_detail: str = ""
    checked_values: dict = Field(default_factory=dict)
